### ISSUE TITLE
Lens object does not create proper device_tuple

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/transfocate#24]
Copied from https://github.com/pcdshub/pcdsdevices/issues/157

## Current Behavior

Currently when you create a `Lens` object and call `.get()` the command fails with an error message such as:
```
__new__() got an unexpected keyword argument 'your_signal'
```
On further investigation, the traceback reveals that this is raised while trying to create a `self._device_tuple` object. If you look at what this object actually is it looks like:
```
YourDeviceTuple(state, _1, _2, _3, _4)
```
I'm guessing the MRO of these class definitions does not produce a `DeviceTuple` that includes the signals attached by the child class. This causes an issue because when `get` tries to fill the tuple with `component_names` there are no spots in the tuple for all the components. It is worth noting that `component_names` contains **all** the signals, probably just not in time for the `_device_tuple` creation. 

## Your Environment

`ophyd == v1.1.0`

**Comment by teddyrendahl** [comment]
Cause by signal names with leading underscores. Chasing this down in `ophyd`.

**Comment by teddyrendahl** [comment]
Closed by https://github.com/NSLS-II/ophyd/pull/515

**Comment by ZLLentz** [comment]
closing issue that is already marked as closed by
