### ISSUE TITLE
using_fake_epics_pv breaks in Travis

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/transfocate#27]
There is an error happening on Travis that I can not reproduce locally. It appears that the `using_fake_epics_pv` wrapper is not catching all our `EpicsSignal` objects.

https://travis-ci.org/pcdshub/transfocate/jobs/382895262

This is confusing as this library uses the packaged `using_fake_epics_pv` from `pcdsdevices`. This should ultimately be replaced by `make_fake_class`

**Comment by ZLLentz** [comment]
closed by #29
